import { Quicksand } from "next/font/google";
import "./globals.css";
import LayoutContext from "./layoutContext";

const quicksand = Quicksand({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LayoutContext>
      <html lang="en">
        <body className={`${quicksand.className} text-black`}>{children}</body>
      </html>
    </LayoutContext>
  );
}
